apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: crane-mutating-webhook
  labels:
    {{- include "crane.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Files.Get "keys/ca.crt" | b64enc }}
      service:
        name: craned
        namespace: {{ .Release.Namespace }}
        path: /mutate-prediction-crane-io-v1alpha1-timeseriesprediction
    failurePolicy: Fail
    name: mprediction.crane.io
    rules:
      - apiGroups:
          - prediction.crane.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - TimeSeriesPrediction
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Files.Get "keys/ca.crt" | b64enc }}
      service:
        name: craned
        namespace: {{ .Release.Namespace }}
        path: /mutate-autoscaling-crane-io-v1alpha1-effectivehorizontalpodautoscaler
    failurePolicy: Fail
    name: mautoscaling.crane.io
    rules:
      - apiGroups:
          - autoscaling.crane.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - EffectiveHorizontalPodAutoscaler
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crane-validating-webhook
  labels:
    {{- include "crane.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Files.Get "keys/ca.crt" | b64enc }}
      service:
        name: craned
        namespace: {{ .Release.Namespace }}
        path: /validate-prediction-crane-io-v1alpha1-timeseriesprediction
    failurePolicy: Fail
    name: vprediction.crane.io
    rules:
      - apiGroups:
          - prediction.crane.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - timeseriespredictions
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Files.Get "keys/ca.crt" | b64enc }}
      service:
        name: craned
        namespace: {{ .Release.Namespace }}
        path: /validate-autoscaling-crane-io-v1alpha1-effectivehorizontalpodautoscaler
    failurePolicy: Fail
    name: vautoscaling.crane.io
    rules:
      - apiGroups:
          - autoscaling.crane.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - effectivehorizontalpodautoscalers
    sideEffects: None
